kind: pipeline
name: oas_cliente_ci


steps:
  - name: install dependencies
    image: node:18
    commands:
      - npm install
    when:
      branch:
        - release/**
      event:
        - push

  # - name: run tests
  #   image: node:18
  #   commands:
  #     - npm run test
  #   when:
  #     branch:
  #       - release/**
  #     event:
  #       - push

  - name: build project
    image: node:18
    commands:
      - npm run build
    when:
      branch:
        - release/**
      event:
        - push

  - name: publish_s3_release
    image: plugins/s3
    settings:
      bucket: cliente-pruebas
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-east-1
      source: dist/**/*
      target: /${DRONE_REPO_NAME}
      strip_prefix: dist/
    when:
      branch:
      - release/*
      event:
      - push
 
  - name: publish_s3_master
    image: plugins/s3
    settings:
      bucket: cliente-prod
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      region: us-east-1
      source: dist/**/*
      target: /${DRONE_REPO_NAME}
      strip_prefix: dist/
    when:
      branch:
      - master
      event:
      - push

# - name: deploy
#   image: alpine
#   commands:
#     - echo "Despliegue aquí"
#   when:
#     branch:
#       include:
#         - release/**
#     event:
#       include:
#         - push