version: "3.8"

services:
  observatorio-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: observatorio-frontend
    ports:
      - "4200:4200"  # Puerto externo 4200 -> interno 80 (nginx)