version: "3.8"

services:
  observatorio-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: observatorio-frontend
    ports:
      - "5173:5173"  # Puerto externo 5173 -> interno 80 (nginx)