# Required metadata
sonar.projectKey=observatorios_cliente
sonar.projectName=observatorios_cliente
sonar.projectVersion=1.0

# Comma-separated paths to directories with sources (required)
sonar.sources=src

sonar.language=js

sonar.inclusions=**/*.js,**/*.ts,**/*.vue

# Encoding of the source files
sonar.sourceEncoding=UTF-8

sonar.exclusions=public/**,node_modules/**,**/*.spec.js,**/*.test.js,**/__tests__/**
